# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
version: 3.0.3
title: Smartling Help
email: your-email@domain.com
description: 
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown


emptyArray: []

editions:
  - Express
  - Basic
  - Standard
  - Growth
  - Enterprise
  - Extra

#Collections

collections:
  articles:
    output: true
    permalink: "/articles/:title/"

  sections:
    output: true
    permalink: "/sections/:title/"

  faqs:
    output: true
    permalink: "/faq/:title/"

