# Hi There!

# Here are some settings for help.smartling.com
# If you change these, remember to rebuild your environments
# so your changes are picked up!

# Also, probably mostly don't change these!

# Cheers,
# Kale


# Site settings
version: 3.0.3
title: Smartling Help
baseurl: ""
url: "http://help.smartling.com/"


# Build settings
markdown: kramdown
highlighter: rouge
incremental: false


# LAYOUT

# Column Widths (must add up to 12)
left-width: 4
right-width: 8




#Collections

collections:

  # Main Support Center
  articles:
    output: true
    permalink: "knowledge-base/articles/:title/"

  sections:
    output: true
    permalink: "knowledge-base/sections/:title/"

  faqs:
    output: true
    permalink: "knowledge-base/faq/:title/"

  # Developers

  filetypes:
    output: true
    permalink: "developers/files/:title/"

  developerarticles:
    output: true
    permalink: "developers/:categories/:title/"

  filedirectives:
    output: false

  v2endpoints:
    output: true
    permalink: "developers/api/v2/:categories/:title/"

  v2sections:
    output: true
    permalink: "developers/api/v2/:title/"

#  terms:
#    output: false
#    permalink: "terms/:title/"

  posts:
    output: true
    permalink: "blog/:categories/:title"

  authors:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:categories/:title/


# CloudCannon Helpers
# These are used to aid front-matter editing in CloudCannon
# Not used to build the actual site

editions:
  - Express
  - Basic
  - Standard
  - Growth
  - Enterprise
  - Extra

blog-authors:
  - Andrew Saxe
  - Eric Negron
  - Katya Kameneva
  - Kunal Sarda
  - Tobias Kahn
  - Kale Bogdanovs

learning_types:
  - Guide
  - Video
  - Best Practice
  - Webinar

example_types:
  - generic
  - json
  - customxml
  - yaml
  - csv

methods:
  - GET
  - POST
  - DELETE

types:
  - string
  - array
  - number
  - boolean

# For Liquid Calcs - DON'T CHANGE
emptyArray: []
navItem: []
homeCardNavItems: []